name: macOS 10.15

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'glib glib-networking gobject-introspection pkg-config jq' }}
  UBUNTU_APT: ${{ 'libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.3'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftGLib
        uses: actions/checkout@v2
        with:
          path: SwiftGLib

      - name: Build Swift Wrappers
        run: |
          cd SwiftGLib
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGLib
        run: |
          cd SwiftGLib
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftGLib
        run: |
          cd SwiftGLib
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftGLib
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-catalina
          path: |
            SwiftGLib/
          retention-days: 1
